#!/bin/sh
# =============================================================================
# entrypoint.sh — генерирует runtime env.js перед стартом nginx.
#
# Назначение:
#   Vite запекает VITE_* переменные в JS-бандл на этапе сборки (build-time).
#   Для K8s-деплоя, где образ собирается один раз и деплоится на несколько
#   окружений, нужен механизм runtime-конфигурации.
#
#   Этот скрипт генерирует /usr/share/nginx/html/env.js со значениями
#   из ENV-переменных контейнера. Фронтенд читает window.__env__ как
#   fallback к import.meta.env.
#
# В K8s env.js монтируется из ConfigMap (subPath) поверх этого файла,
# поэтому скрипт безопасно запускается, но его вывод не виден браузеру.
# Для Docker Compose — файл генерируется из переменных docker-compose.yml.
#
# Переменные:
#   VITE_WS_URL  — WebSocket URL (ws://host/ws/eca или wss://...)
# =============================================================================
set -e

ENV_JS_PATH="/usr/share/nginx/html/env.js"

# Если файл уже примонтирован из ConfigMap (K8s subPath), не перезаписываем.
# Проверяем: файл существует И не пустой → ConfigMap-mount → пропускаем.
if [ -s "${ENV_JS_PATH}" ]; then
    echo "[entrypoint] env.js already present (ConfigMap mount), skipping generation"
else
    echo "[entrypoint] Generating ${ENV_JS_PATH} from environment variables"
    cat > "${ENV_JS_PATH}" <<EOF
// Runtime environment — generated by entrypoint.sh at container startup.
// Source: environment variables injected by Docker Compose or K8s Deployment.
// DO NOT EDIT: this file is auto-generated.
window.__env__ = {
  VITE_WS_URL: "${VITE_WS_URL:-}"
};
EOF
    echo "[entrypoint] env.js generated: VITE_WS_URL=${VITE_WS_URL:-<empty>}"
fi

exec nginx -g "daemon off;"
