-- P6-2: Нативное RANGE-партиционирование tracking_event_log по created_at (помесячно).
--
-- ПОЧЕМУ эта таблица и почему нативное партиционирование:
--   tracking_event_log — единственная из трёх высоконагруженных таблиц, которая безопасно
--   поддаётся нативному партиционированию PostgreSQL 16:
--     • Нет FK из других таблиц на tracking_event_log (намеренно — запись переживает удаление
--       sequence/instance, см. V24 и javadoc TrackingEventLog). Нет FK-ограничений, которые
--       нарушило бы изменение схемы.
--     • Единственный write-путь — port.save() (TrackingEventLogPort); нет UPDATE/DELETE
--       из прикладного кода → истинно append-only, партиция DROP = retention без побочных эффектов.
--     • JPA-сущность TrackingEventLog: @Id Long id с GenerationType.IDENTITY. После перевода на
--       партиционированную таблицу:
--         - GENERATED BY DEFAULT AS IDENTITY на id → INSERT ... RETURNING id работает на
--           партиционированных таблицах начиная с PostgreSQL 10 (и корректно в PG 16);
--         - ddl-auto=validate проверяет наличие колонок и типы, а не точный состав PK constraint;
--           id присутствует в PK (id, created_at) → валидация проходит;
--         - findById(Long id) генерирует WHERE id = ? — PostgreSQL использует ведущую колонку
--           составного PK-индекса (id, created_at) для поиска; id уникален (identity-последовательность),
--           запрос корректно находит ровно одну строку из всех партиций.
--     • Тесты используют ddl-auto=none (BaseIntegrationTest) → Hibernate-валидация в тестах
--       не выполняется; сохранение/чтение работают по той же причине (RETURNING + WHERE id = ?).
--
-- messages и audit_log — НЕ партиционируются нативно (retention-by-deletion, RetentionService):
--   messages: сложные JPQL-запросы в MessageJpaRepository (multiple methods with positional
--     params + exists* queries); конверсия на @IdClass потребовала бы изменений в 5+ методах
--     JPA-репозитория, JPA-адаптере, и нескольких сотнях тестов (MessageJpaRepository — горячий
--     путь ECA-движка критериев).
--   audit_log: в корневом пакете, пишется несколькими модулями через разные адаптеры (sequence,
--     user); AuditLogQueryRepository с paged queries; смена PK потребовала бы координации 5+ классов.
--
-- Стратегия партиционирования:
--   • RANGE по created_at, помесячно (именование tracking_event_log_YYYY_MM);
--   • Партиции: 3 месяца назад, текущий месяц (2026-06), 3 месяца вперёд;
--   • DEFAULT-партиция — ловушка для данных вне именованных диапазонов;
--   • Retention (RetentionService): DROP TABLE старых именованных партиций + CREATE новых вперёд.
--   • Индексы создаются на родительской таблице — автоматически наследуются всеми партициями
--     (существующими и будущими): sequence_id, (aircraft_id, flight_number), instance_id, created_at.

-- ═══════════════════════════════════════════════════════════════════════════════
-- Шаг 1: Создать новую партиционированную таблицу.
--         Временное имя constraint'а (tracking_event_log_partitioned_pkey), чтобы избежать
--         коллизии с уже существующим tracking_event_log_pkey на плоской таблице
--         (constraint-имена уникальны в схеме PostgreSQL).
--         После DROP старой таблицы (шаг 5) и RENAME (шаг 6) старое имя освобождается,
--         и мы переименуем constraint в tracking_event_log_pkey (шаг 6b) →
--         pg_indexes.indexname совпадает с V24, тест V24TrackingEventLogMigrationIntTest проходит.
-- ═══════════════════════════════════════════════════════════════════════════════
CREATE TABLE tracking_event_log_partitioned (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    sequence_id     BIGINT          NOT NULL,
    instance_id     BIGINT,
    aircraft_id     VARCHAR(50)     NOT NULL,
    flight_number   VARCHAR(50),
    event_type      VARCHAR(50)     NOT NULL,
    step_index      INTEGER,
    step_result     VARCHAR(20),
    details_json    JSONB,
    correlation_id  VARCHAR(64),
    created_at      TIMESTAMP       NOT NULL DEFAULT now(),
    CONSTRAINT tracking_event_log_partitioned_pkey PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Шаг 2: Месячные партиции: 3 месяца назад (март–май 2026), текущий месяц,
--         3 месяца вперёд (июль–сентябрь 2026), DEFAULT-партиция.
-- ═══════════════════════════════════════════════════════════════════════════════
CREATE TABLE tracking_event_log_2026_03 PARTITION OF tracking_event_log_partitioned
    FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');

CREATE TABLE tracking_event_log_2026_04 PARTITION OF tracking_event_log_partitioned
    FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');

CREATE TABLE tracking_event_log_2026_05 PARTITION OF tracking_event_log_partitioned
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');

-- Текущий месяц (июнь 2026): сюда попадают все test-записи с created_at = now() в тестах.
CREATE TABLE tracking_event_log_2026_06 PARTITION OF tracking_event_log_partitioned
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');

CREATE TABLE tracking_event_log_2026_07 PARTITION OF tracking_event_log_partitioned
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

CREATE TABLE tracking_event_log_2026_08 PARTITION OF tracking_event_log_partitioned
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

CREATE TABLE tracking_event_log_2026_09 PARTITION OF tracking_event_log_partitioned
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');

-- DEFAULT-партиция: ловушка для данных вне именованных диапазонов.
-- Retention для DEFAULT — DELETE по дате (RetentionService), не DROP TABLE.
CREATE TABLE tracking_event_log_default PARTITION OF tracking_event_log_partitioned DEFAULT;

-- ═══════════════════════════════════════════════════════════════════════════════
-- Шаг 3: Перенос существующих данных из плоской таблицы в партиционированную.
--         GENERATED BY DEFAULT AS IDENTITY допускает явное указание id (BY DEFAULT),
--         поэтому существующие id-значения переносятся без изменений.
--         Данных на момент первого деплоя нет или минимум (тесты сбрасывают БД),
--         но миграция корректна и на заполненной БД (требование CLAUDE.md).
-- ═══════════════════════════════════════════════════════════════════════════════
INSERT INTO tracking_event_log_partitioned
    (id, sequence_id, instance_id, aircraft_id, flight_number,
     event_type, step_index, step_result, details_json, correlation_id, created_at)
SELECT id, sequence_id, instance_id, aircraft_id, flight_number,
       event_type, step_index, step_result, details_json, correlation_id, created_at
FROM tracking_event_log;

-- ═══════════════════════════════════════════════════════════════════════════════
-- Шаг 4: Сдвинуть identity-счётчик за максимальный скопированный id,
--         чтобы следующий INSERT не столкнулся с дублем.
-- ═══════════════════════════════════════════════════════════════════════════════
DO $$
DECLARE
    max_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(id), 0) INTO max_id FROM tracking_event_log_partitioned;
    IF max_id > 0 THEN
        EXECUTE format(
            'ALTER TABLE tracking_event_log_partitioned ALTER COLUMN id RESTART WITH %s',
            max_id + 1
        );
    END IF;
END
$$;

-- ═══════════════════════════════════════════════════════════════════════════════
-- Шаг 5: Удалить старую плоскую таблицу.
--         DROP TABLE каскадно удаляет BIGSERIAL-последовательность tracking_event_log_id_seq
--         и старые индексы. GENERATED BY DEFAULT AS IDENTITY в новой таблице управляет
--         своей последовательностью независимо (нет конфликта имён).
-- ═══════════════════════════════════════════════════════════════════════════════
DROP TABLE tracking_event_log;

-- ═══════════════════════════════════════════════════════════════════════════════
-- Шаг 6: Переименовать партиционированную таблицу в рабочее имя.
-- ═══════════════════════════════════════════════════════════════════════════════
ALTER TABLE tracking_event_log_partitioned RENAME TO tracking_event_log;

-- ═══════════════════════════════════════════════════════════════════════════════
-- Шаг 6b: Вернуть constraint'у финальное имя tracking_event_log_pkey.
--          Теперь старое имя освобождено (DROP TABLE в шаге 5 удалил старый constraint),
--          поэтому коллизии нет. pg_indexes.indexname = 'tracking_event_log_pkey'
--          → тест V24TrackingEventLogMigrationIntTest проходит без изменений.
-- ═══════════════════════════════════════════════════════════════════════════════
ALTER TABLE tracking_event_log
    RENAME CONSTRAINT tracking_event_log_partitioned_pkey TO tracking_event_log_pkey;

-- ═══════════════════════════════════════════════════════════════════════════════
-- Шаг 7: Индексы на РОДИТЕЛЬСКОЙ таблице.
--         PostgreSQL автоматически создаёт производные индексы на каждой существующей
--         партиции и на любой будущей (в отличие от уникальных ограничений).
--         Имена совпадают с именами из V24 → тест V24TrackingEventLogMigrationIntTest
--         (migrationCreatesExpectedIndexes) проходит без изменений.
-- ═══════════════════════════════════════════════════════════════════════════════
CREATE INDEX idx_tracking_event_log_sequence   ON tracking_event_log (sequence_id);
CREATE INDEX idx_tracking_event_log_aircraft   ON tracking_event_log (aircraft_id, flight_number);
CREATE INDEX idx_tracking_event_log_instance   ON tracking_event_log (instance_id);
CREATE INDEX idx_tracking_event_log_created_at ON tracking_event_log (created_at);
