apiVersion: v1
kind: Service
metadata:
  name: {{ include "eca-system.frontendServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eca-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "eca-system.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
